name: Check University Announcements

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rerun_announcement]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/minhoooong/pknu_notice_bot:latest
      credentials:
        username: minhoooong
        password: ${{ secrets.MY_PAT }}
      env:
        PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      
      # ▼▼▼ Git 보안 문제를 해결하기 위해 이 단계를 추가합니다. ▼▼▼
      - name: Set git safe directory
        run: git config --global --add safe.directory /__w/PKNU_Notice_Bot/PKNU_Notice_Bot

      - name: List workspace
        run: |
          echo "Current working directory: $(pwd)"
          ls -la "$(pwd)"

      - name: Unlock git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          export GIT_CRYPT_ALLOW_UNSAFE_REPOSITORY=1
          echo "$GIT_CRYPT_KEY" | base64 -d > keyfile
          git-crypt unlock keyfile

      - name: Run announcement bot script
        env:
          PKNU_USERNAME: ${{ secrets.PKNU_USERNAME }}
          PKNU_PASSWORD: ${{ secrets.PKNU_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 -m app.run_auto_agent

      - name: Trigger workflow re-run
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "rerun_announcement"}'