name: Check University Announcements

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rerun_announcement]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/minhoooong/pknu_notice_bot:latest
      credentials:
        username: minhoooong
        password: ${{ secrets.MY_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      
      - name: Set safe directory explicitly
        run: git config --global --add safe.directory "$PWD"

      - name: List workspace
        run: |
          pwd
          ls -la ${{ github.workspace }}

      # Docker 이미지에 이미 의존성와 git-crypt가 설치되어 있으므로,
      # 별도의 설치 단계는 생략 가능합니다.
      - name: Unlock git-crypt
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          export GIT_CRYPT_ALLOW_UNSAFE_REPOSITORY=1
          git config --global --add safe.directory "${{ github.workspace }}"
          echo "$GIT_CRYPT_KEY" | base64 -d > keyfile
          git-crypt unlock keyfile

      - name: Run announcement bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_PAT: ${{ secrets.MY_PAT }}
          REGISTRATION_CODE: ${{ secrets.REGISTRATION_CODE }}
        run: python3 script.py

      - name: Trigger workflow re-run
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "rerun_announcement"}'
