name: Check University Announcements

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rerun_announcement]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_PAT }}

      - name: Pull the latest docker image
        run: docker pull ghcr.io/minhoooong/pknu_notice_bot:latest

      - name: Unlock git-crypt and Run Script inside the container
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_PAT: ${{ secrets.MY_PAT }}
          REGISTRATION_CODE: ${{ secrets.REGISTRATION_CODE }}
        run: |
          # 1. Docker 컨테이너를 실행하고, 환경변수와 작업 볼륨을 넘겨줍니다.
          # 2. 컨테이너 안에서 git-crypt를 풀고 파이썬 스크립트를 실행합니다.
          docker run --rm \
            --env GIT_CRYPT_KEY \
            --env TELEGRAM_TOKEN \
            --env CHAT_ID \
            --env GROUP_CHAT_ID \
            --env OPENAI_API_KEY \
            --env MY_PAT \
            --env REGISTRATION_CODE \
            --workdir /__w/PKNU_Notice_Bot/PKNU_Notice_Bot \
            --volume "${{ github.workspace }}":/__w/PKNU_Notice_Bot/PKNU_Notice_Bot \
            ghcr.io/minhoooong/pknu_notice_bot:latest \
            /bin/bash -c "export GIT_CRYPT_ALLOW_UNSAFE_REPOSITORY=1 && echo '$GIT_CRYPT_KEY' | base64 -d > keyfile && git-crypt unlock keyfile && python3 script.py"

      - name: Trigger workflow re-run
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "rerun_announcement"}'