name: Check University Announcements

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rerun_announcement]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_PAT }}

      - name: Pull the latest docker image
        run: docker pull ghcr.io/minhoooong/pknu_notice_bot:latest

      - name: Run Script inside the container
        env:
          PKNU_USERNAME: ${{ secrets.PKNU_USERNAME }}
          PKNU_PASSWORD: ${{ secrets.PKNU_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          # Docker 컨테이너를 실행하고, 환경변수와 현재 작업 폴더를 그대로 넘겨줍니다.
          # 컨테이너 안에서 git-crypt를 풀고 파이썬 스크립트를 실행합니다.
          docker run --rm \
            --env-file <(env | grep -E 'PKNU_|TELEGRAM_|GIT_CRYPT_') \
            --workdir /app \
            --volume "${{ github.workspace }}":/app \
            ghcr.io/minhoooong/pknu_notice_bot:latest \
            /bin/bash -c "git config --global --add safe.directory /app && export GIT_CRYPT_ALLOW_UNSAFE_REPOSITORY=1 && echo '$GIT_CRYPT_KEY' | base64 -d > keyfile && git-crypt unlock keyfile && python3 script.py"

      - name: Trigger workflow re-run
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "rerun_announcement"}'
