name: Check University Announcements

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Setup Google Cloud Credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > /tmp/gcloud.json
      shell: bash

    - name: Verify Google Cloud Credentials File
      run: cat /tmp/gcloud.json

    - name: Set environment variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud.json" >> $GITHUB_ENV

    - name: Run announcement bot script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        MY_PAT: ${{ secrets.MY_PAT }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud.json
      run: python script.py

    - name: Clean up credentials
      run: rm -f /tmp/gcloud.json
