name: Check University Announcements

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rerun_announcement]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python & Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Install and unlock git-crypt
        run: |
          sudo apt-get update && sudo apt-get install -y git-crypt
          echo "$GIT_CRYPT_KEY" | base64 -d > keyfile
          git-crypt unlock keyfile
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Run announcement bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_PAT: ${{ secrets.MY_PAT }}
          REGISTRATION_CODE: ${{ secrets.REGISTRATION_CODE }}
        run: python script.py

      - name: Trigger workflow re-run
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "rerun_announcement"}'
