name: Check University Announcements

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행
  workflow_dispatch:

jobs:
  check_announcements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # GitHub 기본 인증 제거

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Authenticate with Personal Access Token (MY_PAT)
        run: |
          git remote set-url origin https://Minhoooong:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}.git

      - name: Pull latest changes
        run: |
          git pull origin main || echo "No changes to pull"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 aiogram

      - name: Run announcement bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MY_PAT: ${{ secrets.MY_PAT }}
        run: python script.py

      - name: Commit and push updates to announcements_seen.json
        run: |
          git add announcements_seen.json
          git commit -m "Update announcements_seen.json" || echo "No changes to commit"
          git push origin main
