name: PKNU AI NonSbjt Auto
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Run auto script
        env:
          PKNU_USERNAME: ${{ secrets.PKNU_USERNAME }}
          PKNU_PASSWORD: ${{ secrets.PKNU_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ALL_TERMS: 'true'
        run: python -m app.run_auto_agent
