name: Run PKNU Notice Bot script
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # hourly schedule; adjust as needed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Playwright (first-run)
        run: python -m playwright install --with-deps
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          PKNU_USERNAME: ${{ secrets.PKNU_USERNAME }}
          PKNU_PASSWORD: ${{ secrets.PKNU_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script.py
